### PR TITLE
Added unit tests for City Service Layer

### PR DESCRIPTION
**Pull request by burakkoken**

### CODE REVIEW

**Comment by burakkoken** [comment]
Unit tests for City Service Layer only were added. City service hasn't been implemented completely yet. That's why when it is built, it's normal to have an Error. If you look at build logs, you can see the what causes the build error. Please, await until the service layer for City Service is completed :+1: Don't close the pull request

**Comment by ozgurustun** [comment]
Can you close reminder for this pull request? If it is not ready to merge you can create code-review issue to check. Do we have to get reminder for 16 times in a day about an not-ready pull request???

**Comment by ozgurustun** [comment]
Is it done?

**Comment by burakkoken** [comment]
I'm done with it! @ozgurustun

**Pull request merged**
